version: "2"
services:
  server:
    container_name: server
    build: .
    ports:
      - "4022:4022"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"