version: "3"
services:
  app:
    container_name: service
    image: calvinminhla/service
    build: .
    restart: always
    ports:
      - "4022:4022"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"